services:
  parking-app:
    image: ghcr.io/wizely99/parking:latest
    container_name: parking-api
    depends_on:
      - parking-db
    environment:
      - SPRING_PROFILES_ACTIVE=herman
      - DB_HOST=${DB_HOST}
      - DB_PORT=${DB_PORT}
      - DB_NAME=${DB_NAME}
      - DB_USERNAME=${DB_USERNAME}
      - DB_PASSWORD=${DB_PASSWORD}
      - MAIL_USERNAME=${MAIL_USERNAME}
      - MAIL_PASSWORD=${MAIL_PASSWORD}
      - KEYCLOAK_SERVER_URL=${KEYCLOAK_SERVER_URL}
      - KEYCLOAK_REALM=${KEYCLOAK_REALM}
      - ADMIN_CLI_CLIENT_SECRET=${ADMIN_CLI_CLIENT_SECRET}
    labels:
      - "com.centurylinklabs.watchtower.enable=true"
      - "traefik.enable=true"
      - "traefik.http.routers.parkingapi.priority=900"
      - "traefik.http.routers.parkingapi.rule=Host(`parking-api.quenchx.com`)"
      - "traefik.http.routers.parkingapi.entrypoints=websecure"
      - "traefik.http.routers.parkingapi.tls.certresolver=production"
      - "traefik.http.routers.parkingapi.tls=true"
      - "traefik.docker.network=traefik_network"

    ports:
      - "8088:8080"
    networks:
      - parking-network
      - "traefik_network"

    restart: unless-stopped


  parking-db:
    image: postgis/postgis:17-3.5-alpine
    container_name: parking-db
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_INITDB_ARGS=--encoding=UTF-8 --lc-collate=C --lc-ctype=C
    ports:
      - "5404:5432"
    networks:
      - parking-network
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ./init-scripts:/docker-entrypoint-initdb.d
    restart: unless-stopped


  parking-frontend:
    image: ghcr.io/wizely99/thesa-loan:latest
    container_name: parking-frontend
    environment:
      - SPRING_API_URL=${SPRING_API_URL}
      - NEXTAUTH_URL=${NEXTAUTH_URL}
      - NEXTAUTH_SECRET=${NEXTAUTH_SECRET}
      - KEYCLOAK_CLIENT_ID=${KEYCLOAK_CLIENT_ID}
      - KEYCLOAK_CLIENT_SECRET=${KEYCLOAK_CLIENT_SECRET}
      - KEYCLOAK_URL=${KEYCLOAK_URL}
      - AUTH_ISSUER=${AUTH_ISSUER}
      - END_SESSION_URL=${END_SESSION_URL}
      - REFRESH_TOKEN_URL=${REFRESH_TOKEN_URL}
      - API_GATEWAY_BASE_URL=example.com
    labels:
      - "com.centurylinklabs.watchtower.enable=true"
      - "traefik.enable=true"
      - "traefik.http.routers.parking.priority=900"
      - "traefik.http.routers.parking.rule=Host(`parking.quenchx.com`)"
      - "traefik.http.routers.parking.entrypoints=websecure"
      - "traefik.http.routers.parking.tls.certresolver=production"
      - "traefik.http.routers.parking.tls=true"
      - "traefik.docker.network=traefik_network"
    ports:
      - "3001:3000"
    depends_on:
      - parking-app

    networks:
      - "traefik_network"
      - parking-network
    restart: unless-stopped


volumes:
  pgdata:
    driver: local
  keycloak_data:
    driver: local

networks:
  parking-network:
    driver: bridge
    name: parking-network
  traefik_network:
    external: true
